# Generated by Django 4.0.4 on 2022-05-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerGasto', '0002_rename_totalamount_asset_importe_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='purpose',
            new_name='proposito',
        ),
    ]
