# Generated by Django 4.0.4 on 2022-05-04 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManagerGasto', '0004_costo_delete_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='Activo',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='date',
            new_name='fecha',
        ),
    ]
