# Generated by Django 4.0.4 on 2022-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerGasto', '0005_rename_asset_activo_rename_date_activo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='importe_Total',
            field=models.DecimalField(decimal_places=1, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='costo',
            name='importe',
            field=models.DecimalField(decimal_places=1, max_digits=100000),
        ),
    ]
